---
name: Ubuntu

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-3_13:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_version: ['3.0', '3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: ${{ matrix.cmake_version }}.x
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate
      run: mkdir ./build; cd ./build; cmake -Werror=dev ..

    - name: Build
      run: cmake --build ./build  --config None


  post-3_13:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_version: ['3.14', '3.15', '3.16', '3.17', '3.18', '3.19', '3.20', '3.21', '3.22', '3.23', '3.24', '3.25']

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: ${{ matrix.cmake_version }}.x
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate
      run: cmake -Werror=dev -S . -B ./build

    - name: Build
      run: cmake --build ./build --parallel 2 --config None
