---
name: Windows

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CMake v3.${{ matrix.cmake_version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: 3.${{ matrix.cmake_version }}.x
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate
      if: ${{ matrix.cmake_version < 13 }}
      run: cmake -E make_directory ./build; cmake -E chdir ./build cmake -Werror=dev -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 12 2013" ..

    - name: Generate
      if: ${{ matrix.cmake_version >= 13 }}
      run: cmake -Werror=dev -S . -B ./build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      if: ${{ matrix.cmake_version < 12 }}
      run: cmake --build ./build  --config Debug

    - name: Build
      if: ${{ matrix.cmake_version >= 12 }}
      run: cmake --build ./build --parallel 2 --config Debug
